'use client';

import { useState } from 'react';
import { runAppraisal } from './actions';
import { baseCaseInputs, resolveCurrencySymbol } from '../../lib/stack/engine/inputs.js';
import { toDisplayValues, toEngineInputs, applyGuards, validate } from './formModel';
import StackForm from './StackForm';
import StackSummary from './StackSummary';
import StackCashflow from './StackCashflow';
import StackComparison from './StackComparison';
import StackSensitivity from './StackSensitivity';
import styles from './stack.module.css';

/**
 * The STACK tool (sub-step 2.3). Holds the form's display values, validates and
 * guards them, runs the appraisal through the server action, and renders the
 * read-only appraisal summary.
 */

export default function StackTool() {
  const [values, setValues] = useState(() => toDisplayValues(baseCaseInputs()));
  const [errors, setErrors] = useState({});
  const [result, setResult] = useState(null);
  const [meta, setMeta] = useState(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState(null);

  const currencySymbol = resolveCurrencySymbol(values.reportingCurrency || 'GBP');

  function handleChange(key, value) {
    setValues((current) => ({ ...current, [key]: value }));
  }

  async function handleSubmit() {
    const found = validate(values);
    setErrors(found);
    if (Object.keys(found).length > 0) return;

    setBusy(true);
    setError(null);
    const engineInputs = toEngineInputs(applyGuards(values));
    const response = await runAppraisal(engineInputs);
    setBusy(false);

    if (response.ok) {
      setResult(response.result);
      setMeta(response.meta);
    } else {
      setError(response.error);
    }
  }

  // Export via the browser's print-to-PDF, the same path the PULSE brief uses.
  // The print stylesheet hides the form and the app chrome and lays out the
  // report only. The engine is never in the download; the figures are static.
  function handleDownloadPdf() {
    if (typeof window === 'undefined') return;
    const label = `Flitrr STACK, ${meta?.strategy ?? ''} appraisal`.trim();
    const previous = document.title;
    document.title = label;
    const restore = () => {
      document.title = previous;
      window.removeEventListener('afterprint', restore);
    };
    window.addEventListener('afterprint', restore);
    window.print();
  }

  const generatedDate = new Date().toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });

  return (
    <div className={styles.tool}>
      <StackForm
        values={values}
        errors={errors}
        currencySymbol={currencySymbol}
        onChange={handleChange}
        onSubmit={handleSubmit}
        busy={busy}
      />

      {error && <p className={styles.error}>{error}</p>}

      {result && (
        <div className={styles.results}>
          <div className={styles.reportHead}>
            <div className={styles.printBanner} aria-hidden="true">
              <span className={styles.printBrand}>Flitrr STACK</span>
              <span className={styles.printReportTitle}>Development appraisal and funding report</span>
              <span className={styles.printMeta}>
                {meta.strategy} scheme, generated {generatedDate}
              </span>
            </div>
            <button type="button" className={styles.downloadBtn} onClick={handleDownloadPdf}>
              Download PDF report
            </button>
          </div>

          <StackSummary result={result} meta={meta} />
          <StackCashflow result={result} meta={meta} />
          <StackComparison result={result} meta={meta} />
          <StackSensitivity result={result} meta={meta} />

          <p className={styles.printStamp} aria-hidden="true">
            Generated by Flitrr STACK on {generatedDate}. This report is licensed for this appraisal
            only and is not to be reused as a live model. Illustrative figures for design purposes,
            not investment, financial or valuation advice.
          </p>
        </div>
      )}
    </div>
  );
}
