-- ========================================================================
-- 014_playbook_seed.sql
--
-- GENERATED by scripts/seed-playbooks.mjs from content/playbooks/*.md
-- (pulse_playbook_stage_2.md, pulse_playbook_stage_3.md). Do not edit by hand: edit the content files and
-- re-run the script, then apply this again in the Supabase SQL editor.
--
-- Idempotent: upserts keyed on slug, so a re-run updates the curated
-- fields in place without changing any play's id (project_playbook_state
-- rows keep pointing at the same plays). Plays removed from content are
-- not deleted here; retiring a play is a deliberate manual migration.
--
-- Run AFTER 013_playbook_engine.sql.
-- ========================================================================

INSERT INTO playbook_plays
  (slug, type, stage, jurisdiction, title, why, objective, always_critical)
VALUES
  ('define-team-needed', 'action'::play_type, 2, 'general', 'Decide which consultants this project actually needs now, and which can wait', 'Over-appointing burns fee budget before the design settles, and under-appointing surfaces later as a refusal or a redesign, so the team list is a decision, not a default.', 'cost'::objective_type, false),
  ('scope-and-fees-against-brief', 'action'::play_type, 2, 'general', 'Check every scope of services and fee against the Brief before signing', 'A consultant scoped from their standard template will deliver their standard service, and a fee without an agreed basis becomes a negotiation after the work is done, so both must be pinned to your Brief before anything is signed.', 'cost'::objective_type, false),
  ('statutory-duty-holders', 'action'::play_type, 2, 'general', 'Confirm the statutory duty holders for your project and appoint them in writing', 'In many jurisdictions the legal duties for construction health and safety sit with you, the client, by default, and unless you formally appoint competent people to the formal roles, an inspector or an incident will find you holding duties you never knew you had.', 'quality'::objective_type, true),
  ('pi-insurance-check', 'action'::play_type, 2, 'general', 'Confirm professional indemnity insurance for every consultant before appointment', 'If a consultant''s design or advice fails years later, their PI insurance is what pays for the fix, so an appointment without verified cover leaves that whole risk sitting on you.', 'quality'::objective_type, true),
  ('written-appointments', 'action'::play_type, 2, 'general', 'Put every appointment in writing before work starts', 'A handshake appointment means the deliverables, the fee, and who owns the drawings are all undefined, and every one of those becomes a dispute precisely when the relationship is under strain.', 'cost'::objective_type, false),
  ('capability-against-objectives', 'action'::play_type, 2, 'general', 'Test each consultant''s track record against your non-negotiable objectives', 'A team that has never delivered your project type at your scale will learn on your money, and in a small firm the partner who pitched is not always the person who delivers, so test the people you will actually get, not the brochure.', 'quality'::objective_type, false),
  ('design-lead-settled', 'action'::play_type, 2, 'general', 'Settle who leads and coordinates the design team', 'When no single consultant owns coordination, every gap between disciplines becomes yours to find, usually on site and at full price.', 'time'::objective_type, false),
  ('design-responsibility-matrix', 'action'::play_type, 2, 'general', 'Agree a design team responsibility matrix', 'Projects rarely stall because the work is hard; they stall because nobody agreed whose decision it was, and a one-page matrix set now prevents weeks of drift later.', 'time'::objective_type, false),
  ('design-licence-secured', 'action'::play_type, 2, 'general', 'Secure your licence to use the design if an appointment ends', 'If you part ways with a consultant who owns the drawings, you can be forced to pay again for work you already funded, so the right to use the design must sit in the terms from day one.', 'cost'::objective_type, false),
  ('funder-reliance-check', 'action'::play_type, 2, 'general', 'Ask your funder what consultant warranties or reliance they will require', 'Funders often need a direct legal route to your consultants, and discovering that after appointments are signed means reopening every contract with no negotiating power.', 'funding'::objective_type, false),
  ('scope-of-services-gap', 'risk'::play_type, 2, 'general', 'Gaps or overlaps between consultant scopes of services', 'When two appointments each assume the other covers a duty, the gap surfaces mid-project as a fee claim or a missed deliverable, and it is always cheaper to close on paper now than on site later.', 'cost'::objective_type, false),
  ('fee-creep-additional-services', 'risk'::play_type, 2, 'general', 'Fees creeping beyond the cost tolerance through additional services', 'Each extra feels small and justified at the time, and the breach only shows when the totals are added, by which point the work is done and the money is owed.', 'cost'::objective_type, false),
  ('relationship-over-capability', 'risk'::play_type, 2, 'general', 'A consultant appointed on relationship rather than capability', 'A familiar face lowers the guard exactly where scrutiny matters most, and the shortfall tends to surface deep in the project where replacement is most disruptive.', 'quality'::objective_type, false),
  ('programme-assumption-clash', 'risk'::play_type, 2, 'general', 'Appointment programmes that quietly contradict the Brief''s time objective', 'If a consultant''s delivery dates do not add up to your completion date, the slip is committed now and merely revealed later.', 'time'::objective_type, false),
  ('survey-before-design', 'action'::play_type, 3, 'general', 'Commission the surveys the design depends on, before the design depends on them', 'A design drawn on assumed ground, hidden services, or an unmeasured site is a design that will be redrawn at your cost, and the ground is where most overruns are born.', 'cost'::objective_type, false),
  ('stage-design-reviews', 'action'::play_type, 3, 'general', 'Review the design against the Brief and the cost plan at the end of every design stage', 'Every line a designer draws commits your money, and a cost plan updated only at the end discovers the overrun after everyone has fallen in love with the design.', 'cost'::objective_type, false),
  ('design-spend-sequencing', 'action'::play_type, 3, 'general', 'Hold detailed design spend until the planning risk is retired', 'Every drawing produced before permission is a bet that permission comes, so spend to the level the approval risk justifies and no further, unless time genuinely demands the gamble.', 'cost'::objective_type, false),
  ('pre-application-engagement', 'action'::play_type, 3, 'general', 'Engage the approving authority before you formally apply', 'An objection you hear in a pre-application meeting costs you a revised drawing, while the same objection in a refusal costs you months and a fresh application.', 'time'::objective_type, false),
  ('conditions-before-celebration', 'action'::play_type, 3, 'general', 'Read, cost, and programme every condition attached to your permission', 'Permission is not the green light; the conditions are, and the ones that must be discharged before you start can take weeks each, so treat them as a workstream from the day the decision lands.', 'time'::objective_type, false),
  ('approvals-beyond-planning', 'action'::play_type, 3, 'general', 'List every approval and connection the build needs, and start the long-lead ones now', 'Planning is rarely the only permission, and utility connections and statutory agreements have lead times measured in months, so the programme is set by the slowest approval you have not started.', 'time'::objective_type, false),
  ('coordinated-buildable-freeze', 'action'::play_type, 3, 'general', 'Demand a coordinated, buildable design before you freeze it', 'Clashes between structure, services, and architecture that are cheap to fix on a drawing are ruinous to fix on site, and an uncoordinated freeze just books that cost for later.', 'quality'::objective_type, false),
  ('value-engineer-by-classification', 'action'::play_type, 3, 'general', 'Value engineer against flexible objectives, and test every cut against the protected ones', 'When the cost plan drifts the savings come from what you classified as able to flex, but every cut must be tested for its knock-on, because a saving that quietly degrades a protected objective only surfaces as failure once the project is delivered.', 'cost'::objective_type, false),
  ('design-freeze-discipline', 'action'::play_type, 3, 'general', 'Freeze the design, then change it only by deliberate decision', 'Some changes are genuinely free, but the expensive ones never announce themselves, so after freeze every change is checked for its cost and time effect before it is agreed, never discovered after it is built.', 'cost'::objective_type, false),
  ('design-cost-drift', 'risk'::play_type, 3, 'general', 'The developing design quietly outgrowing the cost plan', 'Design development adds cost in small, reasonable increments, and without a cost check at each stage the overrun is discovered at tender, when the choices left are all bad ones.', 'cost'::objective_type, false),
  ('planning-outcome-risk', 'risk'::play_type, 3, 'general', 'A planning decision later or worse than the programme assumes', 'Approval timelines are not in your control, and a programme built on the best case turns a routine delay into a funding and contract problem.', 'time'::objective_type, false),
  ('ground-conditions-surprise', 'risk'::play_type, 3, 'general', 'Ground conditions or site constraints the surveys have not derisked', 'What is under the site is the most expensive unknown in development, and it does not negotiate.', 'cost'::objective_type, false),
  ('utility-leadtime-risk', 'risk'::play_type, 3, 'general', 'Utility connections whose lead times outrun the programme', 'A finished building that cannot be powered or drained is not finished, and connection queues do not care about your completion date.', 'time'::objective_type, false)
ON CONFLICT (slug) DO UPDATE SET
  type            = EXCLUDED.type,
  stage           = EXCLUDED.stage,
  jurisdiction    = EXCLUDED.jurisdiction,
  title           = EXCLUDED.title,
  why             = EXCLUDED.why,
  objective       = EXCLUDED.objective,
  always_critical = EXCLUDED.always_critical;
